enable_color: true
enable_depth: true
enable_gyro: true
#enable_infra1: true
#enable_infra2: true
align_depth.enable: true
enable_sync: true
publish_tf: true
tf_publish_rate: 1.0
rgb_camera.color_profile: 640x480x15
depth_module.depth_profile: 640x480x15
